### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dromer** [ContemporaryInsanity/RacketScience#5]
Hey there, I'm interested in including your modules in our [Cardinal](https://github.com/DISTRHO/Cardinal/) project. A statically built FOSS audio plugin based on the Rack2 engine and other opensource projects.

However I'm wondering if your code license is intended as `GPL-3.0-only` or `GPL-3.0-or-later`.

cheers

**Comment by ContemporaryInsanity** [comment]
Hi,

As it stands the repo contains some half finished modules, I got pissed off
with VCV management and abandoned development.  There's not much in there
that other modules don't already cover.  I'd suggest not bothering.

IF I restart development, which is a possibility, I'll let you know.

All the best with Cardinal.

E.

**Comment by dromer** [comment]
Ok! from the description it seemed an interesting bunch and I like your panel designs.

Good luck and hope you make more cool stuff in the future!
